### ISSUE TITLE
Get stuck with USBError, Resource busy etc..

### ISSUE THREAD

**Issue by Peacemaker69** [m1stadev/deleo#8]
I run command to be able to downgrade from 16.7.6 to 16.6 " deleo -t /path/to/blob.shsh /path/to/ipsw LATEST_IPSW " and after it gets stuck with some USB error message, resource busy etc.. Also I run " systemctl stop usbmuxd " and " usbmuxd -p -f ", from before.. 

Did i miss something here ?
![Screenshot_2024-04-05_16-29-58](https://github.com/m1stadev/deleo/assets/5113286/4ecbc7ab-7a3f-4473-a382-9651b6ede439)

**Comment by m1stadev** [comment]
can you run `sudo find / -name '*-libirecovery.rules'` and send the output?

**Comment by Peacemaker69** [comment]
> can you run `sudo find / -name '*-libirecovery.rules'` and send the output?

Sent in a group on discord... :)

**Comment by m1stadev** [comment]
I determined privately that they were attempting to restore with OTA blobs, which requires a pwned restore. deleo doesn't currently support pwned restores, so this issue is being closed for now.
